### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.intel.analytics.bigdl.mkl.MKL.setNumThreads(I)V

### ISSUE THREAD

**Issue by zhangyuansen** [emartinezs44/SparkGCN#6]
If I use windows idea to run the program, an issue occured, is this because I use the Windows
`Exception in thread "main" java.lang.UnsatisfiedLinkError: com.intel.analytics.bigdl.mkl.MKL.setNumThreads(I)V
	at com.intel.analytics.bigdl.mkl.MKL.setNumThreads(Native Method)
	at com.intel.analytics.bigdl.mkl.MKL.setMklEnv(MKL.java:127)
	at com.intel.analytics.bigdl.mkl.MKL.<clinit>(MKL.java:91)
	at com.intel.analytics.bigdl.dllib.tensor.Tensor$.<init>(Tensor.scala:861)
	at com.intel.analytics.bigdl.dllib.tensor.Tensor$.<clinit>(Tensor.scala)
	at com.intel.analytics.bigdl.dllib.nn.abstractnn.Activity$.allocate(Activity.scala:105)
	at com.intel.analytics.bigdl.dllib.nn.abstractnn.AbstractModule.<init>(AbstractModule.scala:69)
	at com.intel.analytics.bigdl.dllib.nn.Container.<init>(Container.scala:42)
	at com.intel.analytics.bigdl.dllib.nn.internal.KerasLayer.<init>(KerasLayer.scala:170)
	at com.intel.analytics.bigdl.dllib.nn.internal.Dropout.<init>(Dropout.scala:39)
	at com.intel.analytics.bigdl.dllib.keras.layers.Dropout.<init>(Dropout.scala:39)
	at com.intel.analytics.bigdl.dllib.keras.layers.Dropout$.apply$mFc$sp(Dropout.scala:55)
	at ems.gcn.model.KerasBased$.getModel(KerasBased.scala:23)
	at ems.gcn.CoraExample$.main(CoraExample.scala:170)
	at ems.gcn.CoraExample.main(CoraExample.scala)`

**Comment by emartinezs44** [comment]
BigDL doesn´t include mkl dll. In the doc they recommend using Windows Subsystem for Linux: https://bigdl.readthedocs.io/en/latest/doc/UserGuide/win.html

**Comment by zhangyuansen** [comment]
thanks very much, then I want to know if I want to output the node vectors, how can I implement it in the code?

**Comment by emartinezs44** [comment]
Do you mean to zip the nodes and the preiction?, in that case you can use the model after training and do predict: 

`completeDatasetRDD.map { sample => (sample, model.predict(Array(sample))) }`
